should_save_offline = true

[[url_action]]
  pattern = "https://news.ycombinator.com"
  match_detection = "starts_with"
  should_save_offline = false
  tags = [3, 2]

[[url_action]]
  pattern = "https://github.com"
  match_detection = "starts_with"
  should_save_offline = false
  tags = [4, 5]
